wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.15
    cli_version: 0.26.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1777023818
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      - 4
      - 13
      - 15
      - 42
      4: 3.11.15
      5: 0.26.0
      13: linux-x86_64
    e:
      cd0dny41rwonlhbyqecqq9v34ngfcg7v:
        os: Linux-6.17.0-14-generic-x86_64-with-glibc2.35
        python: CPython 3.11.15
        started_at: '2026-04-24T09:43:37.868Z'
        program: /home/coder/workspace/shake/redo-by-sara/scripts/log_iid_flower_wandb_plots.py
        code_path: redo-by-sara/scripts/log_iid_flower_wandb_plots.py
        code_path_local: scripts/log_iid_flower_wandb_plots.py
        git:
          remote_url: https://github.com/iamtheeel/shake.git
          commit: e65f5732792e8090dfd37583af27743d71eecc5a
        root: /home/coder/workspace/shake/redo-by-sara
        host: sara-pytorch
        executable: /home/coder/conda/envs/torch311/bin/python
        cpu_count: 16
        cpu_count_logical: 24
        gpu_type: NVIDIA GeForce RTX 3080 Ti
        gpu_count: 1
        disk:
          /:
            total: '1005867986944'
            used: '869690925056'
        memory:
          total: '67200548864'
        gpu_nvidia:
        - name: NVIDIA GeForce RTX 3080 Ti
          memory_total: '12884901888'
          cuda_cores: 10240
          architecture: Ampere
          uuid: GPU-51fc4996-2e7c-d848-b976-5825cc2266fd
        cuda_version: '12.8'
        writer_id: cd0dny41rwonlhbyqecqq9v34ngfcg7v
    visualize:
      classification/test_confusion_matrix_wandb:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: Confusion Matrix Curve
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: classification/test_confusion_matrix_wandb_table
                fields: []
